'use strict';

const _ = require('lodash');

module.exports = _.keyBy([
  {
    name: "Aarakocra",
    size: "Medium", type: "Humanoid", tags: [ "Aarakocra" ],
    ac: 12, hp: 13, init: 2, cr: "1/4",
    environments: [ "mountain", "planar" ],
  },
  {
    name: "Aboleth",
    size: "Large", type: "Aberration",
    ac: 17, hp: 135, init: -1, cr: "10",
    environments: [ "aquatic", "coast" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Angels", name: "Deva",
    size: "Medium", type: "Celestial",
    ac: 17, hp: 136, init: 4, cr: "10",
    environments: [ "planar" ],
  },
  {
    section: "Angels", name: "Planetar",
    size: "Large", type: "Celestial",
    ac: 19, hp: 200, init: 5, cr: "16",
    environments: [ "planar" ],
  },
  {
    section: "Angels", name: "Solar",
    size: "Large", type: "Celestial",
    ac: 21, hp: 241, init: 6, cr: "21",
    environments: [ "planar" ],
    legendary: true,
  },
  {
    section: "Animated Objects", name: "Animated Armor",
    size: "Medium", type: "Construct",
    ac: 18, hp: 33, init: 0, cr: "1",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Animated Objects", name: "Flying Sword",
    size: "Small", type: "Construct",
    ac: 17, hp: 17, init: 2, cr: "1/4",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Animated Objects", name: "Rug of Smothering",
    size: "Large", type: "Construct",
    ac: 12, hp: 33, init: 2, cr: "2",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    name: "Ankheg",
    size: "Large", type: "Monstrosity",
    ac: "14, 11 while prone", hp: 39, init: 0, cr: "2",
    environments: [ "coast", "forest", "grassland", "underground" ],
  },
  {
    name: "Azer",
    size: "Medium", type: "Elemental",
    ac: 17, hp: 39, init: 1, cr: "2",
    environments: [ "underground", "planar" ],
  },
  {
    name: "Banshee",
    size: "Medium", type: "Undead",
    ac: 12, hp: 58, init: 2, cr: "4",
    environments: [ "dungeon", "forest", "ruins", "swamp" ],
  },
  {
    name: "Basilisk",
    size: "Medium", type: "Monstrosity",
    ac: 15, hp: 52, init: -1, cr: "3",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground" ],
  },
  {
    name: "Behir",
    size: "Huge", type: "Monstrosity",
    ac: 17, hp: 168, init: 3, cr: "11",
    environments: [ "cave", "mountain", "underground" ],
  },
  {
    section: "Beholders", name: "Beholder",
    size: "Large", type: "Aberration",
    ac: 18, hp: 180, init: 2, cr: "13",
    environments: [ "cave", "dungeon", "underground" ],
    legendary: true,
    lair: false,
  },
  {
    section: "Beholders", name: "Beholder (in lair)",
    size: "Large", type: "Aberration",
    ac: 18, hp: 180, init: 2, cr: "14",
    environments: [ "cave", "dungeon", "underground" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Beholders", name: "Death Tyrant",
    size: "Large", type: "Undead",
    ac: 19, hp: 187, init: 2, cr: "14",
    environments: [ "cave", "dungeon", "underground" ],
    legendary: true,
    lair: false,
  },
  {
    section: "Beholders", name: "Death Tyrant (in lair)",
    size: "Large", type: "Undead",
    ac: 19, hp: 187, init: 2, cr: "15",
    environments: [ "cave", "dungeon", "underground" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Beholders", name: "Spectator",
    size: "Medium", type: "Aberration",
    ac: 14, hp: 39, init: 2, cr: "3",
    environments: [ "cave", "dungeon", "ruins", "underground", "urban" ],
  },
  {
    section: "Blights", name: "Needle Blight",
    size: "Medium", type: "Plant",
    ac: 12, hp: 11, init: 1, cr: "1/4",
    environments: [ "forest", "grassland", "swamp" ],
  },
  {
    section: "Blights", name: "Twig Blight",
    size: "Small", type: "Plant",
    ac: 13, hp: 4, init: 1, cr: "1/8",
    environments: [ "forest", "grassland", "swamp" ],
  },
  {
    section: "Blights", name: "Vine Blight",
    size: "Medium", type: "Plant",
    ac: 12, hp: 26, init: -1, cr: "1/2",
    environments: [ "forest", "grassland", "swamp" ],
  },
  {
    section: "Bugbears", name: "Bugbear",
    size: "Medium", type: "Humanoid", tags: [ "Goblinoid" ],
    ac: 16, hp: 27, init: 2, cr: "1",
    environments: [ "cave", "dungeon", "forest", "mountain", "ruins", "urban" ],
  },
  {
    section: "Bugbears", name: "Bugbear Chief",
    size: "Medium", type: "Humanoid", tags: [ "Goblinoid" ],
    ac: 17, hp: 65, init: 2, cr: "3",
    environments: [ "cave", "dungeon", "forest", "mountain", "ruins", "urban" ],
  },
  {
    name: "Bulette",
    size: "Large", type: "Monstrosity",
    ac: 17, hp: 94, init: 0, cr: "5",
    environments: [ "cave", "desert", "grassland", "mountain", "underground" ],
  },
  {
    name: "Bullywug",
    size: "Medium", type: "Humanoid", tags: [ "Bullywug" ],
    ac: 15, hp: 11, init: 1, cr: "1/4",
    environments: [ "coast", "swamp" ],
  },
  {
    name: "Cambion",
    size: "Medium", type: "Fiend",
    ac: 19, hp: 82, init: 4, cr: "5",
    environments: [ "dungeon", "urban", "planar" ],
  },
  {
    name: "Carrion Crawler",
    size: "Large", type: "Monstrosity",
    ac: 13, hp: 51, init: 1, cr: "2",
    environments: [ "cave", "dungeon", "underground" ],
  },
  {
    name: "Centaur",
    size: "Large", type: "Monstrosity",
    ac: 12, hp: 45, init: 2, cr: "2",
    environments: [ "coast", "desert", "grassland" ],
  },
  {
    name: "Chimera",
    size: "Large", type: "Monstrosity",
    ac: 14, hp: 114, init: 0, cr: "6",
    environments: [ "mountain" ],
  },
  {
    name: "Chuul",
    size: "Large", type: "Aberration",
    ac: 16, hp: 93, init: 0, cr: "4",
    environments: [ "aquatic", "coast" ],
  },
  {
    name: "Cloaker",
    size: "Large", type: "Aberration",
    ac: 14, hp: 78, init: 2, cr: "8",
    environments: [ "cave", "dungeon", "underground" ],
  },
  {
    name: "Cockatrice",
    size: "Small", type: "Monstrosity",
    ac: 11, hp: 27, init: 1, cr: "1/2",
    environments: [ "forest", "grassland", "swamp" ],
  },
  {
    name: "Couatl",
    size: "Medium", type: "Celestial",
    ac: 19, hp: 97, init: 5, cr: "4",
    environments: [ "planar" ],
  },
  {
    name: "Crawling Claw",
    size: "Tiny", type: "Undead",
    ac: 12, hp: 2, init: 2, cr: "0",
    environments: [ "dungeon", "ruins", "swamp" ],
  },
  {
    name: "Cyclops",
    size: "Huge", type: "Giant",
    ac: 14, hp: 138, init: 0, cr: "6",
    environments: [ "cave", "coast", "grassland", "mountain", "ruins", "swamp" ],
  },
  {
    name: "Darkmantle",
    size: "Small", type: "Monstrosity",
    ac: 11, hp: 22, init: 1, cr: "1/2",
    environments: [ "cave", "underground" ],
  },
  {
    name: "Death Knight",
    size: "Medium", type: "Undead",
    ac: 20, hp: 180, init: 0, cr: "17",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },
  {
    name: "Demilich",
    size: "Tiny", type: "Undead",
    ac: 20, hp: 80, init: 5, cr: "18",
    environments: [ "dungeon" ],
    legendary: true,
    lair: false,
  },
  {
    name: "Demilich (in lair)",
    size: "Tiny", type: "Undead",
    ac: 20, hp: 80, init: 5, cr: "20",
    environments: [ "dungeon" ],
    legendary: true,
    lair: true,
  },
  {
    name: "Demilich (Acererak)",
    size: "Tiny", type: "Undead", unique: true,
    ac: 20, hp: 80, init: 5, cr: "21",
    legendary: true,
    lair: false,
  },
  {
    name: "Demilich (Acererak in lair)",
    size: "Tiny", type: "Undead", unique: true,
    ac: 20, hp: 80, init: 5, cr: "23",
    legendary: true,
    lair: true,
  },
  {
    section: "Demons", name: "Balor",
    size: "Huge", type: "Fiend", tags: [ "Demon" ],
    ac: 19, hp: 262, init: 2, cr: "19",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Barlgura",
    size: "Large", type: "Fiend", tags: [ "Demon" ],
    ac: 15, hp: 68, init: 2, cr: "5",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Chasme",
    size: "Large", type: "Fiend", tags: [ "Demon" ],
    ac: 15, hp: 84, init: 2, cr: "6",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Dretch",
    size: "Small", type: "Fiend", tags: [ "Demon" ],
    ac: 11, hp: 18, init: 0, cr: "1/4",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Glabrezu",
    size: "Large", type: "Fiend", tags: [ "Demon" ],
    ac: 17, hp: 157, init: 2, cr: "9",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Goristro",
    size: "Huge", type: "Fiend", tags: [ "Demon" ],
    ac: 19, hp: 310, init: 0, cr: "17",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Hezrou",
    size: "Large", type: "Fiend", tags: [ "Demon" ],
    ac: 16, hp: 136, init: 3, cr: "8",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Manes",
    size: "Small", type: "Fiend", tags: [ "Demon" ],
    ac: 9, hp: 9, init: -1, cr: "1/8",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Marilith",
    size: "Large", type: "Fiend", tags: [ "Demon" ],
    ac: 18, hp: 189, init: 5, cr: "16",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Nalfeshnee",
    size: "Large", type: "Fiend", tags: [ "Demon" ],
    ac: 18, hp: 184, init: 0, cr: "13",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Quasit",
    size: "Tiny", type: "Fiend", tags: [ "Demon", "Shapechanger" ],
    ac: 13, hp: 7, init: 3, cr: "1",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Shadow Demon",
    size: "Medium", type: "Fiend", tags: [ "Demon" ],
    ac: 13, hp: 66, init: 3, cr: "4",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Vrock",
    size: "Large", type: "Fiend", tags: [ "Demon" ],
    ac: 15, hp: 104, init: 2, cr: "6",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Demons", name: "Yochlol",
    size: "Medium", type: "Fiend", tags: [ "Demon", "Shapechanger" ],
    ac: 15, hp: 136, init: 2, cr: "10",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Devils", name: "Barbed Devil",
    size: "Medium", type: "Fiend", tags: [ "Devil" ],
    ac: 15, hp: 110, init: 3, cr: "5",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Devils", name: "Bearded Devil",
    size: "Medium", type: "Fiend", tags: [ "Devil" ],
    ac: 13, hp: 52, init: 2, cr: "3",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Devils", name: "Bone Devil",
    size: "Large", type: "Fiend", tags: [ "Devil" ],
    ac: 19, hp: 142, init: 3, cr: "9",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Devils", name: "Chain Devil",
    size: "Medium", type: "Fiend", tags: [ "Devil" ],
    ac: 16, hp: 85, init: 2, cr: "8",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Devils", name: "Erinyes",
    size: "Medium", type: "Fiend", tags: [ "Devil" ],
    ac: 18, hp: 153, init: 3, cr: "12",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Devils", name: "Horned Devil",
    size: "Large", type: "Fiend", tags: [ "Devil" ],
    ac: 18, hp: 178, init: 3, cr: "11",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Devils", name: "Ice Devil",
    size: "Large", type: "Fiend", tags: [ "Devil" ],
    ac: 18, hp: 180, init: 2, cr: "14",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Devils", name: "Imp",
    size: "Tiny", type: "Fiend", tags: [ "Demon", "Shapechanger" ],
    ac: 13, hp: 10, init: 3, cr: "1",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Devils", name: "Lemure",
    size: "Medium", type: "Fiend", tags: [ "Devil" ],
    ac: 7, hp: 13, init: -3, cr: "0",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Devils", name: "Pit Fiend",
    size: "Large", type: "Fiend", tags: [ "Devil" ],
    ac: 19, hp: 300, init: 2, cr: "20",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Devils", name: "Spined Devil",
    size: "Small", type: "Fiend", tags: [ "Devil" ],
    ac: 13, hp: 22, init: 2, cr: "2",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Dinosaurs", name: "Allosaurus",
    size: "Large", type: "Beast",
    ac: 13, hp: 51, init: 1, cr: "2",
    environments: [ "coast", "grassland", "swamp" ],
  },
  {
    section: "Dinosaurs", name: "Ankylosaurus",
    size: "Huge", type: "Beast",
    ac: 15, hp: 68, init: 0, cr: "3",
    environments: [ "grassland" ],
  },
  {
    section: "Dinosaurs", name: "Plesiosaurus",
    size: "Large", type: "Beast",
    ac: 13, hp: 68, init: 2, cr: "2",
    environments: [ "aquatic" ],
  },
  {
    section: "Dinosaurs", name: "Pteranodon",
    size: "Medium", type: "Beast",
    ac: 13, hp: 13, init: 2, cr: "1/4",
    environments: [ "mountain" ],
  },
  {
    section: "Dinosaurs", name: "Triceratops",
    size: "Huge", type: "Beast",
    ac: 13, hp: 95, init: -1, cr: "5",
    environments: [ "grassland", "mountain" ],
  },
  {
    section: "Dinosaurs", name: "Tyrannosaurus Rex",
    size: "Huge", type: "Beast",
    ac: 13, hp: 136, init: 0, cr: "8",
    environments: [ "grassland" ],
  },
  {
    name: "Displacer Beast",
    size: "Large", type: "Monstrosity",
    ac: 13, hp: 85, init: 2, cr: "3",
    environments: [ "forest", "grassland" ],
  },
  {
    name: "Doppelganger",
    size: "Medium", type: "Monstrosity", tags: [ "Shapechanger" ],
    ac: 14, hp: 52, init: 4, cr: "3",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Dracolich", name: "Adult Blue Dracolich",
    size: "Huge", type: "Undead",
    ac: 19, hp: 225, init: 0, cr: "17",
    environments: [ "desert", "dungeon" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragon, Shadow", name: "Young Red Shadow Dragon",
    size: "Large", type: "Dragon",
    ac: 18, hp: 178, init: 0, cr: "13",
    environments: [ "planar" ],
  },
  {
    section: "Dragons", name: "Adult Black Dragon",
    size: "Huge", type: "Dragon",
    ac: 19, hp: 195, init: 2, cr: "14",
    environments: [ "swamp" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Adult Blue Dragon",
    size: "Huge", type: "Dragon",
    ac: 19, hp: 225, init: 0, cr: "16",
    environments: [ "desert" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Adult Brass Dragon",
    size: "Huge", type: "Dragon",
    ac: 18, hp: 172, init: 0, cr: "13",
    environments: [ "cave", "underground" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Adult Bronze Dragon",
    size: "Huge", type: "Dragon",
    ac: 19, hp: 212, init: 0, cr: "15",
    environments: [ "coast" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Adult Copper Dragon",
    size: "Huge", type: "Dragon",
    ac: 18, hp: 184, init: 1, cr: "14",
    environments: [ "cave", "desert", "grassland" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Adult Gold Dragon",
    size: "Huge", type: "Dragon",
    ac: 19, hp: 256, init: 2, cr: "17",
    environments: [ "mountain", "ruins" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Adult Green Dragon",
    size: "Huge", type: "Dragon",
    ac: 19, hp: 207, init: 1, cr: "15",
    environments: [ "forest" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Adult Red Dragon",
    size: "Huge", type: "Dragon",
    ac: 19, hp: 256, init: 0, cr: "17",
    environments: [ "mountain" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Adult Silver Dragon",
    size: "Huge", type: "Dragon",
    ac: 19, hp: 243, init: 0, cr: "16",
    environments: [ "arctic", "mountain" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Adult White Dragon",
    size: "Huge", type: "Dragon",
    ac: 18, hp: 200, init: 0, cr: "13",
    environments: [ "arctic", "cave", "underground" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Ancient Black Dragon",
    size: "Gargantuan", type: "Dragon",
    ac: 22, hp: 367, init: 2, cr: "21",
    environments: [ "swamp" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Ancient Blue Dragon",
    size: "Gargantuan", type: "Dragon",
    ac: 22, hp: 481, init: 0, cr: "23",
    environments: [ "desert" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Ancient Brass Dragon",
    size: "Gargantuan", type: "Dragon",
    ac: 20, hp: 297, init: 0, cr: "20",
    environments: [ "cave", "underground" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Ancient Bronze Dragon",
    size: "Gargantuan", type: "Dragon",
    ac: 22, hp: 444, init: 0, cr: "22",
    environments: [ "coast" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Ancient Copper Dragon",
    size: "Gargantuan", type: "Dragon",
    ac: 21, hp: 350, init: 1, cr: "21",
    environments: [ "cave", "desert", "grassland" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Ancient Gold Dragon",
    size: "Gargantuan", type: "Dragon",
    ac: 22, hp: 546, init: 2, cr: "24",
    environments: [ "mountain", "ruins" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Ancient Green Dragon",
    size: "Gargantuan", type: "Dragon",
    ac: 21, hp: 385, init: 1, cr: "22",
    environments: [ "forest" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Ancient Red Dragon",
    size: "Gargantuan", type: "Dragon",
    ac: 22, hp: 546, init: 0, cr: "24",
    environments: [ "mountain" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Ancient Silver Dragon",
    size: "Gargantuan", type: "Dragon",
    ac: 22, hp: 487, init: 0, cr: "23",
    environments: [ "arctic", "mountain" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Ancient White Dragon",
    size: "Gargantuan", type: "Dragon",
    ac: 20, hp: 333, init: 0, cr: "20",
    environments: [ "arctic", "cave", "underground" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Dragons", name: "Black Dragon Wyrmling",
    size: "Medium", type: "Dragon",
    ac: 17, hp: 33, init: 2, cr: "2",
    environments: [ "swamp" ],
  },
  {
    section: "Dragons", name: "Blue Dragon Wyrmling",
    size: "Medium", type: "Dragon",
    ac: 17, hp: 52, init: 0, cr: "3",
    environments: [ "desert" ],
  },
  {
    section: "Dragons", name: "Brass Dragon Wyrmling",
    size: "Medium", type: "Dragon",
    ac: 16, hp: 16, init: 0, cr: "1",
    environments: [ "cave", "underground" ],
  },
  {
    section: "Dragons", name: "Bronze Dragon Wyrmling",
    size: "Medium", type: "Dragon",
    ac: 17, hp: 32, init: 0, cr: "2",
    environments: [ "coast" ],
  },
  {
    section: "Dragons", name: "Copper Dragon Wyrmling",
    size: "Medium", type: "Dragon",
    ac: 16, hp: 22, init: 1, cr: "1",
    environments: [ "cave", "desert", "grassland" ],
  },
  {
    section: "Dragons", name: "Gold Dragon Wyrmling",
    size: "Medium", type: "Dragon",
    ac: 17, hp: 60, init: 2, cr: "3",
    environments: [ "mountain", "ruins" ],
  },
  {
    section: "Dragons", name: "Green Dragon Wyrmling",
    size: "Medium", type: "Dragon",
    ac: 17, hp: 38, init: 1, cr: "2",
    environments: [ "forest" ],
  },
  {
    section: "Dragons", name: "Red Dragon Wyrmling",
    size: "Medium", type: "Dragon",
    ac: 17, hp: 75, init: 0, cr: "4",
    environments: [ "mountain" ],
  },
  {
    section: "Dragons", name: "Silver Dragon Wyrmling",
    size: "Medium", type: "Dragon",
    ac: 17, hp: 45, init: 0, cr: "2",
    environments: [ "arctic", "mountain" ],
  },
  {
    section: "Dragons", name: "White Dragon Wyrmling",
    size: "Medium", type: "Dragon",
    ac: 16, hp: 32, init: 0, cr: "2",
    environments: [ "arctic", "cave", "underground" ],
  },
  {
    section: "Dragons", name: "Young Black Dragon",
    size: "Large", type: "Dragon",
    ac: 18, hp: 127, init: 2, cr: "7",
    environments: [ "swamp" ],
  },
  {
    section: "Dragons", name: "Young Blue Dragon",
    size: "Large", type: "Dragon",
    ac: 18, hp: 152, init: 0, cr: "9",
    environments: [ "desert" ],
  },
  {
    section: "Dragons", name: "Young Brass Dragon",
    size: "Large", type: "Dragon",
    ac: 17, hp: 110, init: 0, cr: "6",
    environments: [ "cave", "underground" ],
  },
  {
    section: "Dragons", name: "Young Bronze Dragon",
    size: "Large", type: "Dragon",
    ac: 18, hp: 142, init: 0, cr: "8",
    environments: [ "coast" ],
  },
  {
    section: "Dragons", name: "Young Copper Dragon",
    size: "Large", type: "Dragon",
    ac: 17, hp: 119, init: 1, cr: "7",
    environments: [ "cave", "desert", "grassland" ],
  },
  {
    section: "Dragons", name: "Young Gold Dragon",
    size: "Large", type: "Dragon",
    ac: 18, hp: 178, init: 2, cr: "10",
    environments: [ "mountain", "ruins" ],
  },
  {
    section: "Dragons", name: "Young Green Dragon",
    size: "Large", type: "Dragon",
    ac: 18, hp: 136, init: 1, cr: "8",
    environments: [ "forest" ],
  },
  {
    section: "Dragons", name: "Young Red Dragon",
    size: "Large", type: "Dragon",
    ac: 18, hp: 178, init: 0, cr: "10",
    environments: [ "mountain" ],
  },
  {
    section: "Dragons", name: "Young Silver Dragon",
    size: "Large", type: "Dragon",
    ac: 18, hp: 168, init: 0, cr: "9",
    environments: [ "arctic", "mountain" ],
  },
  {
    section: "Dragons", name: "Young White Dragon",
    size: "Large", type: "Dragon",
    ac: 17, hp: 133, init: 0, cr: "6",
    environments: [ "arctic", "cave", "underground" ],
  },
  {
    name: "Dragon Turtle",
    size: "Gargantuan", type: "Dragon",
    ac: 20, hp: 341, init: 0, cr: "17",
    environments: [ "aquatic" ],
  },
  {
    name: "Drider",
    size: "Large", type: "Monstrosity",
    ac: 19, hp: 123, init: 3, cr: "6",
    environments: [ "dungeon", "underground" ],
  },
  {
    name: "Dryad",
    size: "Medium", type: "Fey",
    ac: "11 (16 with barkskin)", hp: 22, init: 1, cr: "1",
    environments: [ "forest" ],
  },
  {
    name: "Duergar",
    size: "Medium", type: "Humanoid", tags: [ "Dwarf" ],
    ac: 16, hp: 26, init: 0, cr: "1",
    environments: [ "dungeon", "underground" ],
  },
  {
    section: "Elementals", name: "Air Elemental",
    size: "Large", type: "Elemental",
    ac: 15, hp: 90, init: 5, cr: "5",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "planar" ],
  },
  {
    section: "Elementals", name: "Earth Elemental",
    size: "Large", type: "Elemental",
    ac: 17, hp: 126, init: -1, cr: "5",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "planar" ],
  },
  {
    section: "Elementals", name: "Fire Elemental",
    size: "Large", type: "Elemental",
    ac: 13, hp: 102, init: 3, cr: "5",
    environments: [ "cave", "coast", "desert", "dungeon", "grassland", "mountain", "ruins", "underground", "planar" ],
  },
  {
    section: "Elementals", name: "Water Elemental",
    size: "Large", type: "Elemental",
    ac: 14, hp: 114, init: 2, cr: "5",
    environments: [ "aquatic", "arctic", "cave", "coast", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "planar" ],
  },
  {
    section: "Elves: Drow", name: "Drow",
    size: "Medium", type: "Humanoid", tags: [ "Elf" ],
    ac: 15, hp: 13, init: 2, cr: "1/4",
    environments: [ "dungeon", "underground", "urban" ],
  },
  {
    section: "Elves: Drow", name: "Drow Elite Warrior",
    size: "Medium", type: "Humanoid", tags: [ "Elf" ],
    ac: 18, hp: 71, init: 4, cr: "5",
    environments: [ "dungeon", "underground", "urban" ],
  },
  {
    section: "Elves: Drow", name: "Drow Mage",
    size: "Medium", type: "Humanoid", tags: [ "Elf" ],
    ac: "12 (15 with mage armor)", hp: 45, init: 2, cr: "7",
    environments: [ "dungeon", "underground", "urban" ],
  },
  {
    section: "Elves: Drow", name: "Drow Priestess of Lolth",
    size: "Medium", type: "Humanoid", tags: [ "Elf" ],
    ac: 16, hp: 71, init: 2, cr: "8",
    environments: [ "dungeon", "underground", "urban" ],
  },
  {
    name: "Empyrean",
    size: "Huge", type: "Celestial", tags: [ "Titan" ],
    ac: 22, hp: 313, init: 5, cr: "23",
    environments: [ "planar" ],
    legendary: true,
  },
  {
    name: "Ettercap",
    size: "Medium", type: "Monstrosity",
    ac: 13, hp: 44, init: 2, cr: "2",
    environments: [ "cave", "dungeon", "forest", "ruins", "swamp", "underground" ],
  },
  {
    name: "Ettin",
    size: "Large", type: "Giant",
    ac: 12, hp: 85, init: -1, cr: "4",
    environments: [ "cave", "grassland", "mountain", "swamp" ],
  },
  {
    name: "Faerie Dragon (red)",
    size: "Tiny", type: "Dragon",
    ac: 15, hp: 14, init: 5, cr: "1",
    environments: [ "forest", "grassland", "mountain", "ruins", "swamp" ],
  },
  {
    name: "Faerie Dragon (orange)",
    size: "Tiny", type: "Dragon",
    ac: 15, hp: 14, init: 5, cr: "1",
    environments: [ "forest", "grassland", "mountain", "ruins", "swamp" ],
  },
  {
    name: "Faerie Dragon (yellow)",
    size: "Tiny", type: "Dragon",
    ac: 15, hp: 14, init: 5, cr: "1",
    environments: [ "forest", "grassland", "mountain", "ruins", "swamp" ],
  },
  {
    name: "Faerie Dragon (green)",
    size: "Tiny", type: "Dragon",
    ac: 15, hp: 14, init: 5, cr: "2",
    environments: [ "forest", "grassland", "mountain", "ruins", "swamp" ],
  },
  {
    name: "Faerie Dragon (blue)",
    size: "Tiny", type: "Dragon",
    ac: 15, hp: 14, init: 5, cr: "2",
    environments: [ "forest", "grassland", "mountain", "ruins", "swamp" ],
  },
  {
    name: "Faerie Dragon (indigo)",
    size: "Tiny", type: "Dragon",
    ac: 15, hp: 14, init: 5, cr: "2",
    environments: [ "forest", "grassland", "mountain", "ruins", "swamp" ],
  },
  {
    name: "Faerie Dragon (violet)",
    size: "Tiny", type: "Dragon",
    ac: 15, hp: 14, init: 5, cr: "2",
    environments: [ "forest", "grassland", "mountain", "ruins", "swamp" ],
  },
  {
    name: "Flameskull",
    size: "Tiny", type: "Undead",
    ac: 13, hp: 40, init: 3, cr: "4",
    environments: [ "dungeon", "ruins" ],
  },
  {
    name: "Flumph",
    size: "Small", type: "Aberration",
    ac: 12, hp: 7, init: 2, cr: "1/8",
    environments: [ "dungeon", "underground" ],
  },
  {
    name: "Fomorian",
    size: "Huge", type: "Giant",
    ac: 14, hp: 149, init: 0, cr: "8",
    environments: [ "cave", "underground" ],
  },
  {
    name: "Galeb Duhr",
    size: "Medium", type: "Elemental",
    ac: 16, hp: 85, init: 2, cr: "6",
    environments: [ "cave", "dungeon", "mountain", "underground", "planar" ],
  },
  {
    section: "Fungi", name: "Gas Spore",
    size: "Large", type: "Plant",
    ac: 5, hp: 1, init: -5, cr: "1/2",
    environments: [ "cave", "dungeon", "underground" ],
  },
  {
    section: "Fungi", name: "Shrieker",
    size: "Medium", type: "Plant",
    ac: 5, hp: 13, init: -5, cr: "0",
    environments: [ "cave", "dungeon", "swamp" ],
  },
  {
    section: "Fungi", name: "Violet Fungus",
    size: "Medium", type: "Plant",
    ac: 5, hp: 18, init: -5, cr: "1/4",
    environments: [ "cave", "dungeon", "underground" ],
  },
  {
    name: "Gargoyle",
    size: "Medium", type: "Elemental",
    ac: 15, hp: 52, init: 0, cr: "2",
    environments: [ "dungeon", "urban" ],
  },
  {
    section: "Genies", name: "Dao",
    size: "Large", type: "Elemental",
    ac: 18, hp: 187, init: 1, cr: "11",
    environments: [ "cave", "dungeon", "mountain", "underground", "planar" ],
  },
  {
    section: "Genies", name: "Djinni",
    size: "Large", type: "Elemental",
    ac: 17, hp: 161, init: 2, cr: "11",
    environments: [ "arctic", "coast", "dungeon", "grassland", "planar" ],
  },
  {
    section: "Genies", name: "Efreeti",
    size: "Large", type: "Elemental",
    ac: 17, hp: 200, init: 1, cr: "11",
    environments: [ "desert", "dungeon", "mountain", "planar" ],
  },
  {
    section: "Genies", name: "Marid",
    size: "Large", type: "Elemental",
    ac: 17, hp: 229, init: 1, cr: "11",
    environments: [ "aquatic", "coast", "dungeon", "swamp", "planar" ],
  },
  {
    name: "Ghost",
    size: "Medium", type: "Undead",
    ac: 11, hp: 45, init: 1, cr: "4",
    environments: [ "cave", "dungeon", "ruins", "swamp", "underground", "urban" ],
  },
  {
    section: "Ghouls", name: "Ghast",
    size: "Medium", type: "Undead",
    ac: 13, hp: 36, init: 3, cr: "2",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },

  {
    section: "Ghouls", name: "Ghoul",
    size: "Medium", type: "Undead",
    ac: 12, hp: 22, init: 2, cr: "1",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },
  {
    section: "Giants", name: "Cloud Giant",
    size: "Huge", type: "Giant",
    ac: 14, hp: 200, init: 0, cr: "9",
    environments: [ "mountain", "planar" ],
  },
  {
    section: "Giants", name: "Fire Giant",
    size: "Huge", type: "Giant",
    ac: 18, hp: 162, init: -1, cr: "9",
    environments: [ "mountain", "planar" ],
  },
  {
    section: "Giants", name: "Frost Giant",
    size: "Huge", type: "Giant",
    ac: 15, hp: 138, init: -1, cr: "8",
    environments: [ "arctic", "mountain", "planar" ],
  },
  {
    section: "Giants", name: "Hill Giant",
    size: "Huge", type: "Giant",
    ac: 13, hp: 105, init: -1, cr: "5",
    environments: [ "arctic", "coast", "grassland" ],
  },
  {
    section: "Giants", name: "Stone Giant",
    size: "Huge", type: "Giant",
    ac: 17, hp: 126, init: 2, cr: "7",
    environments: [ "cave", "mountain", "underground" ],
  },
  {
    section: "Giants", name: "Storm Giant",
    size: "Huge", type: "Giant",
    ac: 16, hp: 230, init: 2, cr: "13",
    environments: [ "arctic", "coast", "desert", "mountain", "planar" ],
  },
  {
    name: "Gibbering Mouther",
    size: "Medium", type: "Aberration",
    ac: 9, hp: 67, init: -1, cr: "2",
    environments: [ "cave", "dungeon", "underground", "planar" ],
  },
  {
    section: "Gith", name: "Githyanki Knight",
    size: "Medium", type: "Humanoid", tags: [ "Gith" ],
    ac: 18, hp: 91, init: 2, cr: "8",
    environments: [ "xswamp", "planar" ],
  },
  {
    section: "Gith", name: "Githyanki Warrior",
    size: "Medium", type: "Humanoid", tags: [ "Gith" ],
    ac: 17, hp: 49, init: 2, cr: "3",
    environments: [ "planar" ],
  },
  {
    section: "Gith", name: "Githzerai Monk",
    size: "Medium", type: "Humanoid", tags: [ "Gith" ],
    ac: 14, hp: 38, init: 2, cr: "2",
    environments: [ "planar" ],
  },
  {
    section: "Gith", name: "Githzerai Zerth",
    size: "Medium", type: "Humanoid", tags: [ "Gith" ],
    ac: 17, hp: 84, init: 4, cr: "6",
    environments: [ "planar" ],
  },
  {
    section: "Gnolls", name: "Gnoll",
    size: "Medium", type: "Humanoid", tags: [ "Gnoll" ],
    ac: 15, hp: 22, init: 1, cr: "1/2",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "urban" ],
  },
  {
    section: "Gnolls", name: "Gnoll Fang of Yeenoghu",
    size: "Medium", type: "Fiend", tags: [ "Gnoll" ],
    ac: 14, hp: 65, init: 2, cr: "4",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "urban" ],
  },
  {
    section: "Gnolls", name: "Gnoll Pack Lord",
    size: "Medium", type: "Humanoid", tags: [ "Gnoll" ],
    ac: 15, hp: 49, init: 2, cr: "2",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "urban" ],
  },
  {
    section: "Gnome, Deep (Svirfneblin)", name: "Deep Gnome (Svirfneblin)",
    size: "Small", type: "Humanoid", tags: [ "Gnome" ],
    ac: 15, hp: 16, init: 2, cr: "1/2",
    environments: [ "cave", "dungeon", "underground", "planar" ],
  },
  {
    section: "Goblins", name: "Goblin",
    size: "Small", type: "Humanoid", tags: [ "Goblinoid" ],
    ac: 15, hp: 7, init: 2, cr: "1/4",
    environments: [ "cave", "dungeon", "forest", "grassland", "mountain", "ruins", "urban" ],
  },
  {
    section: "Goblins", name: "Goblin Boss",
    size: "Small", type: "Humanoid", tags: [ "Goblinoid" ],
    ac: 17, hp: 21, init: 2, cr: "1",
    environments: [ "cave", "dungeon", "forest", "grassland", "mountain", "ruins", "urban" ],
  },
  {
    section: "Golems", name: "Clay Golem",
    size: "Large", type: "Construct",
    ac: 14, hp: 133, init: -1, cr: "9",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Golems", name: "Flesh Golem",
    size: "Medium", type: "Construct",
    ac: 9, hp: 93, init: -1, cr: "5",
    environments: [ "dungeon", "ruins" ],
  },
  {
    section: "Golems", name: "Iron Golem",
    size: "Large", type: "Construct",
    ac: 20, hp: 210, init: -1, cr: "16",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Golems", name: "Stone Golem",
    size: "Large", type: "Construct",
    ac: 17, hp: 178, init: -1, cr: "10",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    name: "Gorgon",
    size: "Large", type: "Monstrosity",
    ac: 19, hp: 114, init: 0, cr: "5",
    environments: [ "mountain", "ruins" ],
  },
  {
    name: "Grell",
    size: "Medium", type: "Aberration",
    ac: 12, hp: 55, init: 2, cr: "3",
    environments: [ "dungeon", "underground" ],
  },
  {
    section: "Grick", name: "Grick",
    size: "Medium", type: "Monstrosity",
    ac: 14, hp: 27, init: 2, cr: "2",
    environments: [ "cave", "dungeon", "underground" ],
  },
  {
    section: "Grick", name: "Grick Alpha",
    size: "Large", type: "Monstrosity",
    ac: 18, hp: 75, init: 3, cr: "7",
    environments: [ "cave", "dungeon", "underground" ],
  },
  {
    name: "Griffon",
    size: "Large", type: "Monstrosity",
    ac: 12, hp: 59, init: 2, cr: "2",
    environments: [ "arctic", "coast", "grassland", "mountain" ],
  },
  {
    name: "Grimlock",
    size: "Medium", type: "Humanoid", tags: [ "Grimlock" ],
    ac: 11, hp: 11, init: 1, cr: "1/4",
    environments: [ "cave", "dungeon", "underground" ],
  },
  {
    section: "Hags", name: "Green Hag",
    size: "Medium", type: "Fey",
    ac: 17, hp: 82, init: 1, cr: "3",
    environments: [ "forest", "swamp" ],
  },
  {
    section: "Hags", name: "Green Hag (coven)",
    size: "Medium", type: "Fey",
    ac: 17, hp: 82, init: 1, cr: "5",
    environments: [ "forest", "swamp" ],
  },
  {
    section: "Hags", name: "Night Hag",
    size: "Medium", type: "Fiend",
    ac: 17, hp: 112, init: 2, cr: "5",
    environments: [ "underground", "planar" ],
  },
  {
    section: "Hags", name: "Night Hag (coven)",
    size: "Medium", type: "Fiend",
    ac: 17, hp: 112, init: 2, cr: "7",
    environments: [ "underground", "planar" ],
  },
  {
    section: "Hags", name: "Sea Hag",
    size: "Medium", type: "Fey",
    ac: 14, hp: 52, init: 1, cr: "2",
    environments: [ "aquatic", "coast", "underground" ],
  },
  {
    section: "Hags", name: "Sea Hag (coven)",
    size: "Medium", type: "Fey",
    ac: 14, hp: 52, init: 1, cr: "4",
    environments: [ "aquatic", "coast", "underground" ],
  },
  {
    section: "Half-Dragon", name: "Half-Red Dragon Veteran",
    size: "Medium", type: "Humanoid", tags: [ "Human" ],
    ac: 18, hp: 65, init: 1, cr: "5",
    environments: [ "arctic", "coast", "desert", "grassland", "mountain", "urban" ],
  },
  {
    name: "Harpy",
    size: "Medium", type: "Monstrosity",
    ac: 11, hp: 38, init: 1, cr: "1",
    environments: [ "coast", "forest", "mountain" ],
  },
  {
    name: "Hell Hound",
    size: "Medium", type: "Fiend",
    ac: 15, hp: 45, init: 1, cr: "3",
    environments: [ "dungeon", "urban", "planar" ],
  },
  {
    name: "Helmed Horror",
    size: "Medium", type: "Construct",
    ac: 20, hp: 60, init: 1, cr: "4",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Hobgoblins", name: "Hobgoblin",
    size: "Medium", type: "Humanoid", tags: [ "Goblinoid" ],
    ac: 18, hp: 11, init: 1, cr: "1/2",
    environments: [ "arctic", "coast", "grassland", "mountain", "urban" ],
  },
  {
    section: "Hobgoblins", name: "Hobgoblin Captain",
    size: "Medium", type: "Humanoid", tags: [ "Goblinoid" ],
    ac: 17, hp: 39, init: 2, cr: "3",
    environments: [ "arctic", "coast", "grassland", "mountain", "urban" ],
  },
  {
    section: "Hobgoblins", name: "Hobgoblin Warlord",
    size: "Medium", type: "Humanoid", tags: [ "Goblinoid" ],
    ac: 20, hp: 97, init: 2, cr: "6",
    environments: [ "arctic", "coast", "grassland", "mountain", "urban" ],
  },
  {
    name: "Hippogriff",
    size: "Large", type: "Monstrosity",
    ac: 11, hp: 19, init: 1, cr: "1",
    environments: [ "mountain" ],
  },
  {
    name: "Homunculus",
    size: "Tiny", type: "Construct",
    ac: 13, hp: 5, init: 2, cr: "0",
    environments: [ "dungeon", "urban" ],
  },
  {
    name: "Hook Horror",
    size: "Large", type: "Monstrosity",
    ac: 15, hp: 75, init: 0, cr: "3",
    environments: [ "dungeon", "underground" ],
  },
  {
    name: "Hydra",
    size: "Huge", type: "Monstrosity",
    ac: 15, hp: 172, init: 1, cr: "8",
    environments: [ "aquatic", "cave", "coast", "dungeon", "forest", "mountain", "ruins", "swamp", "underground" ],
  },
  {
    name: "Intellect Devourer",
    size: "Tiny", type: "Aberration",
    ac: 12, hp: 21, init: 2, cr: "2",
    environments: [ "dungeon", "underground" ],
  },
  {
    name: "Invisible Stalker",
    size: "Medium", type: "Elemental",
    ac: 14, hp: 104, init: 4, cr: "6",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban", "planar" ],
  },
  {
    name: "Jackalwere",
    size: "Medium", type: "Humanoid", tags: [ "Shapechanger" ],
    ac: 12, hp: 18, init: 2, cr: "1/2",
    environments: [ "desert", "grassland", "urban" ],
  },
  {
    name: "Kenku",
    size: "Medium", type: "Humanoid", tags: [ "Kenku" ],
    ac: 13, hp: 13, init: 3, cr: "1/4",
    environments: [ "arctic", "coast", "desert", "forest", "grassland", "mountain", "ruins", "urban" ],
  },
  {
    section: "Kobolds", name: "Kobold",
    size: "Small", type: "Humanoid", tags: [ "Kobold" ],
    ac: 12, hp: 5, init: 2, cr: "1/8",
    environments: [ "cave", "dungeon", "mountain", "underground" ],
  },
  {
    section: "Kobolds", name: "Winged Kobold",
    size: "Small", type: "Humanoid", tags: [ "Kobold" ],
    ac: 13, hp: 7, init: 3, cr: "1/4",
    environments: [ "mountain", "underground" ],
  },
  {
    name: "Kraken",
    size: "Gargantuan", type: "Monstrosity", tags: [ "Titan" ],
    ac: 18, hp: 472, init: 0, cr: "23",
    environments: [ "aquatic", "coast" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Kuo-toa", name: "Kuo-toa",
    size: "Medium", type: "Humanoid", tags: [ "Kuo-toa" ],
    ac: 13, hp: 18, init: 0, cr: "1/4",
    environments: [ "aquatic", "coast" ],
  },
  {
    section: "Kuo-toa", name: "Kuo-toa Archpriest",
    size: "Medium", type: "Humanoid", tags: [ "Kuo-toa" ],
    ac: 13, hp: 97, init: 2, cr: "6",
    environments: [ "aquatic", "coast" ],
  },
  {
    section: "Kuo-toa", name: "Kuo-toa Whip",
    size: "Medium", type: "Humanoid", tags: [ "Kuo-toa" ],
    ac: 11, hp: 65, init: 0, cr: "1",
    environments: [ "aquatic", "coast" ],
  },
  {
    name: "Lamia",
    size: "Large", type: "Monstrosity",
    ac: 13, hp: 97, init: 1, cr: "4",
    environments: [ "desert", "ruins" ],
  },
  {
    section: "Lizardfolk", name: "Lizardfolk",
    size: "Medium", type: "Humanoid", tags: [ "Lizardfolk" ],
    ac: 15, hp: 22, init: 0, cr: "1/2",
    environments: [ "coast", "dungeon", "forest", "grassland", "swamp" ],
  },
  {
    section: "Lizardfolk", name: "Lizardfolk Shaman",
    size: "Medium", type: "Humanoid", tags: [ "Lizardfolk" ],
    ac: 13, hp: 27, init: 0, cr: "2",
    environments: [ "coast", "dungeon", "forest", "grassland", "swamp" ],
  },
  {
    section: "Lizardfolk", name: "Lizard King/Queen",
    size: "Medium", type: "Humanoid", tags: [ "Lizardfolk" ],
    ac: 15, hp: 75, init: 1, cr: "4",
    environments: [ "coast", "dungeon", "forest", "grassland", "swamp" ],
  },
  {
    section: "Lycanthropes", name: "Werebear",
    size: "Medium", type: "Humanoid", tags: [ "Human", "Shapechanger" ],
    ac: "10 in humanoid form, 11 in bear and hybrid form", hp: 135, init: 0, cr: "5",
    environments: [ "cave", "forest", "mountain", "urban" ],
  },
  {
    section: "Lycanthropes", name: "Wereboar",
    size: "Medium", type: "Humanoid", tags: [ "Human", "Shapechanger" ],
    ac: "10 in humanoid form, 11 in boar and hybrid form", hp: 78, init: 0, cr: "4",
    environments: [ "forest", "grassland", "swamp", "urban" ],
  },
  {
    section: "Lycanthropes", name: "Wererat",
    size: "Medium", type: "Humanoid", tags: [ "Human", "Shapechanger" ],
    ac: 12, hp: 33, init: 2, cr: "2",
    environments: [ "cave", "dungeon", "ruins", "swamp", "underground", "urban" ],
  },
  {
    section: "Lycanthropes", name: "Weretiger",
    size: "Medium", type: "Humanoid", tags: [ "Human", "Shapechanger" ],
    ac: 12, hp: 120, init: 2, cr: "4",
    environments: [ "forest", "urban" ],
  },
  {
    section: "Lycanthropes", name: "Werewolf",
    size: "Medium", type: "Humanoid", tags: [ "Human", "Shapechanger" ],
    ac: "11 in humanoid form, 12 in wolf or hybrid form", hp: 58, init: 1, cr: "3",
    environments: [ "dungeon", "forest", "grassland", "urban" ],
  },
  {
    name: "Lich",
    size: "Medium", type: "Undead",
    ac: 17, hp: 135, init: 3, cr: "21",
    environments: [ "dungeon", "ruins", "urban" ],
    legendary: true,
    lair: false,
  },
  {
    name: "Lich (in lair)",
    size: "Medium", type: "Undead",
    ac: 17, hp: 135, init: 3, cr: "22",
    environments: [ "dungeon", "ruins", "urban" ],
    legendary: true,
    lair: true,
  },
  {
    name: "Magmin",
    size: "Small", type: "Elemental",
    ac: 14, hp: 9, init: 2, cr: "1/2",
    environments: [ "dungeon", "ruins", "urban", "planar" ],
  },
  {
    name: "Manticore",
    size: "Large", type: "Monstrosity",
    ac: 14, hp: 68, init: 3, cr: "3",
    environments: [ "arctic", "cave", "coast", "grassland", "mountain", "ruins" ],
  },
  {
    name: "Medusa",
    size: "Medium", type: "Monstrosity",
    ac: 15, hp: 127, init: 2, cr: "6",
    environments: [ "cave", "dungeon", "mountain", "ruins", "urban" ],
  },
  {
    section: "Mephits", name: "Dust Mephit",
    size: "Small", type: "Elemental",
    ac: 12, hp: 17, init: 2, cr: "1/2",
    environments: [ "dungeon", "ruins", "urban", "planar" ],
  },
  {
    section: "Mephits", name: "Ice Mephit",
    size: "Small", type: "Elemental",
    ac: 11, hp: 21, init: 1, cr: "1/2",
    environments: [ "arctic", "dungeon", "urban", "planar" ],
  },
  {
    section: "Mephits", name: "Magma Mephit",
    size: "Small", type: "Elemental",
    ac: 11, hp: 22, init: 1, cr: "1/2",
    environments: [ "cave", "dungeon", "mountain", "urban", "planar" ],
  },
  {
    section: "Mephits", name: "Mud Mephit",
    size: "Small", type: "Elemental",
    ac: 11, hp: 27, init: 1, cr: "1/4",
    environments: [ "coast", "dungeon", "forest", "swamp", "urban", "planar" ],
  },
  {
    section: "Mephits", name: "Smoke Mephit",
    size: "Small", type: "Elemental",
    ac: 12, hp: 2, init: 2, cr: "1/4",
    environments: [ "dungeon", "urban", "planar" ],
  },
  {
    section: "Mephits", name: "Steam Mephit",
    size: "Small", type: "Elemental",
    ac: 10, hp: 21, init: 0, cr: "1/4",
    environments: [ "dungeon", "urban", "planar" ],
  },
  {
    name: "Merfolk",
    size: "Medium", type: "Humanoid", tags: [ "Merfolk" ],
    ac: 11, hp: 11, init: 1, cr: "1/8",
    environments: [ "aquatic" ],
  },
  {
    name: "Merrow",
    size: "Large", type: "Monstrosity",
    ac: 13, hp: 45, init: 0, cr: "2",
    environments: [ "aquatic" ],
  },
  {
    section: "Mind Flayer", name: "Mind Flayer",
    size: "Medium", type: "Aberration",
    ac: 15, hp: 71, init: 1, cr: "7",
    environments: [ "dungeon", "underground", "urban" ],
  },
  {
    section: "Mind Flayer", name: "Mind Flayer Arcanist",
    size: "Medium", type: "Aberration",
    ac: 15, hp: 71, init: 1, cr: "8",
    environments: [ "dungeon", "underground", "urban" ],
  },
  {
    name: "Mimic",
    size: "Medium", type: "Monstrosity", tags: [ "Shapechanger" ],
    ac: 12, hp: 58, init: 1, cr: "2",
    environments: [ "dungeon" ],
  },
  {
    name: "Minotaur",
    size: "Large", type: "Monstrosity",
    ac: 14, hp: 76, init: 0, cr: "3",
    environments: [ "cave", "dungeon", "ruins", "underground" ],
  },
  {
    section: "Modrons", name: "Monodrone",
    size: "Medium", type: "Construct",
    ac: 15, hp: 5, init: 1, cr: "1/8",
    environments: [ "planar" ],
  },
  {
    section: "Modrons", name: "Duodrone",
    size: "Medium", type: "Construct",
    ac: 15, hp: 11, init: 1, cr: "1/4",
    environments: [ "planar" ],
  },
  {
    section: "Modrons", name: "Tridrone",
    size: "Medium", type: "Construct",
    ac: 15, hp: 16, init: 1, cr: "1/2",
    environments: [ "planar" ],
  },
  {
    section: "Modrons", name: "Quadrone",
    size: "Medium", type: "Construct",
    ac: 16, hp: 22, init: 2, cr: "1",
    environments: [ "planar" ],
  },
  {
    section: "Modrons", name: "Pentadrone",
    size: "Large", type: "Construct",
    ac: 16, hp: 32, init: 2, cr: "2",
    environments: [ "planar" ],
  },
  {
    section: "Mummies", name: "Mummy",
    size: "Medium", type: "Undead",
    ac: 11, hp: 58, init: -1, cr: "3",
    environments: [ "desert", "dungeon" ],
  },
  {
    section: "Mummies", name: "Mummy Lord",
    size: "Medium", type: "Undead",
    ac: 17, hp: 97, init: 0, cr: "15",
    environments: [ "desert", "dungeon" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Myconids", name: "Myconid Sprout",
    size: "Small", type: "Plant",
    ac: 10, hp: 7, init: 0, cr: "0",
    environments: [ "underground" ],
  },
  {
    section: "Myconids", name: "Quaggoth Spore Servant",
    size: "Medium", type: "Plant",
    ac: 13, hp: 45, init: 1, cr: "1",
    environments: [ "underground" ],
  },
  {
    section: "Myconids", name: "Myconid Adult",
    size: "Medium", type: "Plant",
    ac: 12, hp: 22, init: 0, cr: "1/2",
    environments: [ "underground" ],
  },
  {
    section: "Myconids", name: "Myconid Sovereign",
    size: "Large", type: "Plant",
    ac: 13, hp: 60, init: 0, cr: "2",
    environments: [ "underground" ],
  },
  {
    section: "Nagas", name: "Bone Naga",
    size: "Large", type: "Undead",
    ac: 15, hp: 58, init: 3, cr: "4",
    environments: [ "dungeon", "ruins" ],
  },
  {
    section: "Nagas", name: "Guardian Naga",
    size: "Large", type: "Monstrosity",
    ac: 15, hp: 75, init: 3, cr: "10",
    environments: [ "cave", "coast", "forest", "ruins" ],
  },
  {
    section: "Nagas", name: "Spirit Naga",
    size: "Large", type: "Monstrosity",
    ac: 18, hp: 127, init: 4, cr: "8",
    environments: [ "cave", "dungeon", "ruins", "underground" ],
  },
  {
    name: "Nightmare",
    size: "Large", type: "Fiend",
    ac: 13, hp: 68, init: 2, cr: "3",
    environments: [ "swamp", "planar" ],
  },
  {
    name: "Nothic",
    size: "Medium", type: "Aberration",
    ac: 15, hp: 45, init: 3, cr: "2",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Ogres", name: "Half-Ogre",
    size: "Large", type: "Giant",
    ac: 12, hp: 30, init: 0, cr: "1",
    environments: [ "arctic", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "urban" ],
  },
  {
    section: "Ogres", name: "Ogre",
    size: "Large", type: "Giant",
    ac: 11, hp: 59, init: -1, cr: "2",
    environments: [ "dungeon", "forest", "mountain", "swamp" ],
  },
  {
    name: "Oni",
    size: "Large", type: "Giant",
    ac: 16, hp: 110, init: 0, cr: "7",
    environments: [ "dungeon", "grassland", "ruins", "urban" ],
  },
  {
    section: "Oozes", name: "Black Pudding",
    size: "Large", type: "Ooze",
    ac: 7, hp: 85, init: -3, cr: "4",
    environments: [ "dungeon" ],
  },
  {
    section: "Oozes", name: "Gelatinous Cube",
    size: "Large", type: "Ooze",
    ac: 6, hp: 84, init: -4, cr: "2",
    environments: [ "dungeon" ],
  },
  {
    section: "Oozes", name: "Gray Ooze",
    size: "Medium", type: "Ooze",
    ac: 8, hp: 22, init: -2, cr: "1/2",
    environments: [ "dungeon" ],
  },
  {
    section: "Oozes", name: "Ochre Jelly",
    size: "Large", type: "Ooze",
    ac: 8, hp: 45, init: -2, cr: "2",
    environments: [ "dungeon" ],
  },
  {
    section: "Orcs", name: "Orc",
    size: "Medium", type: "Humanoid", tags: [ "Orc" ],
    ac: 13, hp: 15, init: 1, cr: "1/2",
    environments: [ "arctic", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "urban" ],
  },
  {
    section: "Orcs", name: "Orc Eye of Gruumsh",
    size: "Medium", type: "Humanoid", tags: [ "Orc" ],
    ac: 16, hp: 45, init: 1, cr: "2",
    environments: [ "arctic", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "urban" ],
  },
  {
    section: "Orcs", name: "Orc War Chief",
    size: "Medium", type: "Humanoid", tags: [ "Orc" ],
    ac: 16, hp: 93, init: 1, cr: "4",
    environments: [ "arctic", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "urban" ],
  },
  {
    section: "Orcs", name: "Orog",
    size: "Medium", type: "Humanoid", tags: [ "Orc" ],
    ac: 18, hp: 42, init: 1, cr: "2",
    environments: [ "arctic", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "urban" ],
  },
  {
    name: "Otyugh",
    size: "Large", type: "Aberration",
    ac: 14, hp: 114, init: 0, cr: "5",
    environments: [ "cave", "dungeon", "ruins", "swamp", "underground" ],
  },
  {
    name: "Owlbear",
    size: "Large", type: "Monstrosity",
    ac: 13, hp: 59, init: 1, cr: "3",
    environments: [ "forest", "mountain" ],
  },
  {
    name: "Pegasus",
    size: "Large", type: "Celestial",
    ac: 12, hp: 59, init: 2, cr: "2",
    environments: [ "mountain" ],
  },
  {
    name: "Peryton",
    size: "Large", type: "Monstrosity",
    ac: 13, hp: 33, init: 1, cr: "2",
    environments: [ "mountain" ],
  },
  {
    name: "Piercer",
    size: "Medium", type: "Monstrosity",
    ac: 15, hp: 22, init: 1, cr: "1/2",
    environments: [ "cave", "underground" ],
  },
  {
    name: "Pixie",
    size: "Tiny", type: "Fey",
    ac: 15, hp: 1, init: 5, cr: "1/4",
    environments: [ "coast", "forest", "grassland", "swamp" ],
  },
  {
    name: "Pseudodragon",
    size: "Tiny", type: "Dragon",
    ac: 13, hp: 7, init: 2, cr: "1/4",
    environments: [ "urban" ],
  },
  {
    name: "Purple Worm",
    size: "Gargantuan", type: "Monstrosity",
    ac: 18, hp: 247, init: -2, cr: "15",
    environments: [ "underground" ],
  },
  {
    section: "Quaggoth", name: "Quaggoth",
    size: "Medium", type: "Humanoid", tags: [ "Quaggoth" ],
    ac: 13, hp: 45, init: 1, cr: "2",
    environments: [ "dungeon", "urban" ],
  },
  {
    section: "Quaggoth", name: "Quaggoth Thonot",
    size: "Medium", type: "Humanoid", tags: [ "Quaggoth" ],
    ac: 13, hp: 45, init: 1, cr: "3",
    environments: [ "dungeon", "urban" ],
  },
  {
    name: "Rakshasa",
    size: "Medium", type: "Fiend",
    ac: 16, hp: 110, init: 3, cr: "13",
    environments: [ "urban", "planar" ],
  },
  {
    section: "Remorhazes", name: "Remorhaz",
    size: "Huge", type: "Monstrosity",
    ac: 17, hp: 195, init: 1, cr: "11",
    environments: [ "arctic" ],
  },
  {
    section: "Remorhazes", name: "Young Remorhaz",
    size: "Large", type: "Monstrosity",
    ac: 14, hp: 93, init: 1, cr: "5",
    environments: [ "arctic", "cave" ],
  },
  {
    name: "Revenant",
    size: "Medium", type: "Undead",
    ac: 13, hp: 136, init: 2, cr: "5",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },
  {
    name: "Roc",
    size: "Gargantuan", type: "Monstrosity",
    ac: 15, hp: 248, init: 0, cr: "11",
    environments: [ "coast", "desert", "mountain" ],
  },
  {
    name: "Roper",
    size: "Large", type: "Monstrosity",
    ac: 20, hp: 93, init: -1, cr: "5",
    environments: [ "cave", "underground" ],
  },
  {
    name: "Rust Monster",
    size: "Medium", type: "Monstrosity",
    ac: 14, hp: 27, init: 1, cr: "1/2",
    environments: [ "dungeon", "underground" ],
  },
  {
    section: "Sahuagin", name: "Sahuagin",
    size: "Medium", type: "Humanoid", tags: [ "Sahuagin" ],
    ac: 12, hp: 22, init: 0, cr: "1/2",
    environments: [ "aquatic", "coast" ],
  },
  {
    section: "Sahuagin", name: "Sahuagin Baron",
    size: "Large", type: "Humanoid", tags: [ "Sahuagin" ],
    ac: 16, hp: 76, init: 2, cr: "5",
    environments: [ "aquatic", "coast" ],
  },
  {
    section: "Sahuagin", name: "Sahuagin Priestess",
    size: "Medium", type: "Humanoid", tags: [ "Sahuagin" ],
    ac: 12, hp: 33, init: 0, cr: "2",
    environments: [ "aquatic", "coast" ],
  },
  {
    section: "Salamanders", name: "Fire Snake",
    size: "Medium", type: "Elemental",
    ac: 14, hp: 22, init: 2, cr: "1",
    environments: [ "forest", "planar" ],
  },
  {
    section: "Salamanders", name: "Salamander",
    size: "Large", type: "Elemental",
    ac: 15, hp: 90, init: 2, cr: "5",
    environments: [ "forest", "planar" ],
  },
  {
    name: "Satyr",
    size: "Medium", type: "Fey",
    ac: 14, hp: 31, init: 3, cr: "1/2",
    environments: [ "forest", "grassland", "urban" ],
  },
  {
    name: "Scarecrow",
    size: "Medium", type: "Construct",
    ac: 11, hp: 36, init: 1, cr: "1",
    environments: [ "grassland", "urban" ],
  },
  {
    name: "Shadow",
    size: "Medium", type: "Undead",
    ac: 12, hp: 16, init: 2, cr: "1/2",
    environments: [ "dungeon", "ruins", "swamp", "urban" ],
  },
  {
    name: "Shambling Mound",
    size: "Large", type: "Plant",
    ac: 15, hp: 136, init: -1, cr: "5",
    environments: [ "forest", "swamp" ],
  },
  {
    name: "Shield Guardian",
    size: "Large", type: "Construct",
    ac: 17, hp: 142, init: -1, cr: "7",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Skeletons", name: "Skeleton",
    size: "Medium", type: "Undead",
    ac: 13, hp: 13, init: 2, cr: "1/4",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Skeletons", name: "Minotaur Skeleton",
    size: "Large", type: "Undead",
    ac: 12, hp: 67, init: 0, cr: "2",
    environments: [ "dungeon", "underground", "urban" ],
  },
  {
    section: "Skeletons", name: "Warhorse Skeleton",
    size: "Large", type: "Undead",
    ac: 13, hp: 22, init: 1, cr: "1/2",
    environments: [ "grassland", "ruins" ],
  },
  {
    section: "Slaadi", name: "Blue Slaad",
    size: "Large", type: "Aberration",
    ac: 15, hp: 123, init: 2, cr: "7",
    environments: [ "planar" ],
  },
  {
    section: "Slaadi", name: "Gray Slaad",
    size: "Medium", type: "Aberration",
    ac: 18, hp: 127, init: 3, cr: "9",
    environments: [ "planar" ],
  },
  {
    section: "Slaadi", name: "Green Slaad",
    size: "Large", type: "Aberration",
    ac: 16, hp: 127, init: 2, cr: "8",
    environments: [ "planar" ],
  },
  {
    section: "Slaadi", name: "Red Slaad",
    size: "Large", type: "Aberration",
    ac: 14, hp: 93, init: 1, cr: "5",
    environments: [ "planar" ],
  },
  {
    section: "Slaadi", name: "Slaad Tadpole",
    size: "Tiny", type: "Aberration",
    ac: 12, hp: 10, init: 2, cr: "1/8",
    environments: [ "planar" ],
  },
  {
    section: "Slaadi", name: "Death Slaad",
    size: "Medium", type: "Aberration", tags: [ "Shapechanger" ],
    ac: 18, hp: 170, init: 2, cr: "10",
    environments: [ "planar" ],
  },
  {
    section: "Specter", name: "Poltergeist",
    size: "Medium", type: "Undead",
    ac: 12, hp: 22, init: 2, cr: "2",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Specter", name: "Specter",
    size: "Medium", type: "Undead",
    ac: 12, hp: 22, init: 2, cr: "1",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Sphinxes", name: "Androsphinx",
    size: "Large", type: "Monstrosity",
    ac: 17, hp: 199, init: 0, cr: "17",
    environments: [ "dungeon", "ruins" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Sphinxes", name: "Gynosphinx",
    size: "Large", type: "Monstrosity",
    ac: 17, hp: 136, init: 2, cr: "11",
    environments: [ "dungeon", "ruins" ],
    legendary: true,
    lair: true,
  },
  {
    name: "Sprite",
    size: "Tiny", type: "Fey",
    ac: 15, hp: 2, init: 4, cr: "1/4",
    environments: [ "forest", "grassland", "swamp" ],
  },
  {
    name: "Stirge",
    size: "Tiny", type: "Beast",
    ac: 14, hp: 2, init: 3, cr: "1/8",
    environments: [ "forest", "swamp" ],
  },
  {
    name: "Succubus/Incubus",
    size: "Medium", type: "Fiend", tags: [ "Shapechanger" ],
    ac: 15, hp: 66, init: 3, cr: "4",
    environments: [ "dungeon", "urban", "planar" ],
  },
  {
    name: "Tarrasque",
    size: "Gargantuan", type: "Monstrosity",
    ac: 25, hp: 676, init: 0, cr: "30",
    environments: [ "aquatic", "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban", "planar" ],
    legendary: true,
  },
  {
    name: "Thri-kreen",
    size: "Medium", type: "Humanoid", tags: [ "Thri-kreen" ],
    ac: 15, hp: 33, init: 2, cr: "1",
    environments: [ "desert", "grassland" ],
  },
  {
    name: "Treant",
    size: "Huge", type: "Plant",
    ac: 16, hp: 138, init: -1, cr: "9",
    environments: [ "forest", "swamp" ],
  },
  {
    name: "Troglodyte",
    size: "Medium", type: "Humanoid", tags: [ "Troglodyte" ],
    ac: 11, hp: 13, init: 0, cr: "1/4",
    environments: [ "cave", "dungeon", "underground" ],
  },
  {
    name: "Troll",
    size: "Large", type: "Giant",
    ac: 15, hp: 84, init: 1, cr: "5",
    environments: [ "cave", "dungeon", "forest", "mountain", "swamp" ],
  },
  {
    name: "Umber Hulk",
    size: "Large", type: "Monstrosity",
    ac: 18, hp: 93, init: 1, cr: "5",
    environments: [ "cave", "underground" ],
  },
  {
    name: "Unicorn",
    size: "Large", type: "Celestial",
    ac: 12, hp: 67, init: 2, cr: "5",
    environments: [ "forest", "ruins" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Vampires", name: "Vampire",
    size: "Medium", type: "Undead", tags: [ "Shapechanger" ],
    ac: 16, hp: 144, init: 4, cr: "13",
    environments: [ "dungeon", "ruins", "urban" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Vampires", name: "Vampire Spawn",
    size: "Medium", type: "Undead",
    ac: 15, hp: 82, init: 3, cr: "5",
    environments: [ "dungeon", "ruins", "urban" ],
  },
  {
    section: "Vampires", name: "Vampire Spellcaster",
    size: "Medium", type: "Undead", tags: [ "Shapechanger" ],
    ac: 16, hp: 144, init: 4, cr: "15",
    environments: [ "dungeon", "ruins", "urban" ],
    legendary: true,
    lair: true,
  },
  {
    section: "Vampires", name: "Vampire Warrior",
    size: "Medium", type: "Undead", tags: [ "Shapechanger" ],
    ac: 18, hp: 144, init: 4, cr: "15",
    environments: [ "dungeon", "ruins", "urban" ],
    legendary: true,
    lair: true,
  },
  {
    name: "Water Weird",
    size: "Large", type: "Elemental",
    ac: 13, hp: 58, init: 3, cr: "3",
    environments: [ "cave", "coast", "forest", "mountain", "swamp", "underground", "planar" ],
  },
  {
    name: "Wight",
    size: "Medium", type: "Undead",
    ac: 14, hp: 45, init: 2, cr: "3",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },
  {
    name: "Will-o'-Wisp",
    size: "Tiny", type: "Undead",
    ac: 19, hp: 22, init: 9, cr: "2",
    environments: [ "swamp" ],
  },
  {
    name: "Wraith",
    size: "Medium", type: "Undead",
    ac: 13, hp: 67, init: 3, cr: "5",
    environments: [ "dungeon", "ruins", "swamp", "urban" ],
  },
  {
    name: "Wyvern",
    size: "Large", type: "Dragon",
    ac: 13, hp: 110, init: 0, cr: "6",
    environments: [ "arctic", "coast", "grassland" ],
  },
  {
    name: "Xorn",
    size: "Medium", type: "Elemental",
    ac: 19, hp: 73, init: 0, cr: "5",
    environments: [ "dungeon", "underground", "planar" ],
  },
  {
    section: "Yeti", name: "Abominable Yeti",
    size: "Huge", type: "Monstrosity",
    ac: 15, hp: 137, init: 0, cr: "9",
    environments: [ "arctic", "cave", "mountain" ],
  },
  {
    section: "Yeti", name: "Yeti",
    size: "Large", type: "Monstrosity",
    ac: 12, hp: 51, init: 1, cr: "3",
    environments: [ "arctic", "cave", "mountain" ],
  },
  {
    section: "Yuan-ti", name: "Yuan-ti Abomination",
    size: "Large", type: "Monstrosity", tags: [ "Shapechanger", "Yuan-ti" ],
    ac: 15, hp: 127, init: 3, cr: "7",
    environments: [ "desert", "forest", "mountain", "ruins", "swamp" ],
  },
  {
    section: "Yuan-ti", name: "Yuan-ti Malison",
    size: "Medium", type: "Monstrosity", tags: [ "Shapechanger", "Yuan-ti" ],
    ac: 12, hp: 66, init: 2, cr: "3",
    environments: [ "desert", "forest", "mountain", "ruins", "swamp" ],
  },
  {
    section: "Yuan-ti", name: "Yuan-ti Pureblood",
    size: "Medium", type: "Monstrosity", tags: [ "Yuan-ti" ],
    ac: 11, hp: 40, init: 1, cr: "1",
    environments: [ "desert", "forest", "mountain", "ruins", "swamp" ],
  },
  {
    section: "Yugoloths", name: "Arcanaloth",
    size: "Medium", type: "Fiend", tags: [ "Yugoloth" ],
    ac: 17, hp: 104, init: 1, cr: "12",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Yugoloths", name: "Mezzoloth",
    size: "Medium", type: "Fiend", tags: [ "Yugoloth" ],
    ac: 8, hp: 75, init: 0, cr: "5",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Yugoloths", name: "Nycaloth",
    size: "Large", type: "Fiend", tags: [ "Yugoloth" ],
    ac: 18, hp: 123, init: 0, cr: "9",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Yugoloths", name: "Ultraloth",
    size: "Medium", type: "Fiend", tags: [ "Yugoloth" ],
    ac: 19, hp: 153, init: 3, cr: "13",
    environments: [ "dungeon", "planar" ],
  },
  {
    section: "Zombies", name: "Beholder Zombie",
    size: "Large", type: "Undead",
    ac: 15, hp: 93, init: -1, cr: "5",
    environments: [ "cave", "dungeon", "underground" ],
  },
  {
    section: "Zombies", name: "Ogre Zombie",
    size: "Large", type: "Undead",
    ac: 8, hp: 85, init: -2, cr: "2",
    environments: [ "dungeon", "forest", "mountain", "swamp" ],
  },
  {
    section: "Zombies", name: "Zombie",
    size: "Medium", type: "Undead",
    ac: 8, hp: 22, init: -2, cr: "1/4",
    environments: [ "aquatic", "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },

  // Monster Manual Appendix: Miscellaneous Creatures

  {
    section: "Misc Creatures", name: "Ape",
    size: "Medium", type: "Beast",
    ac: 12, hp: 19, init: 2, cr: "1/2",
    environments: [ "forest" ],
  },
  {
    section: "Misc Creatures", name: "Awakened Shrub",
    size: "Small", type: "Plant",
    ac: 9, hp: 10, init: -1, cr: "0",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Awakened Tree",
    size: "Huge", type: "Plant",
    ac: 13, hp: 59, init: -2, cr: "2",
    environments: [ "forest" ],
  },
  {
    section: "Misc Creatures", name: "Axe Beak",
    size: "Large", type: "Beast",
    ac: 11, hp: 19, init: 1, cr: "1/4",
    environments: [ "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Baboon",
    size: "Small", type: "Beast",
    ac: 12, hp: 3, init: 2, cr: "0",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Badger",
    size: "Tiny", type: "Beast",
    ac: 10, hp: 3, init: 0, cr: "0",
    environments: [ "forest" ],
  },
  {
    section: "Misc Creatures", name: "Bat",
    size: "Tiny", type: "Beast",
    ac: 12, hp: 1, init: 2, cr: "0",
    environments: [ "cave", "forest", "mountain", "underground", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Black Bear",
    size: "Medium", type: "Beast",
    ac: 11, hp: 19, init: 0, cr: "1/2",
    environments: [ "cave", "forest", "grassland", "mountain" ],
  },
  {
    section: "Misc Creatures", name: "Blink Dog",
    size: "Medium", type: "Fey",
    ac: 13, hp: 22, init: 3, cr: "1/4",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Blood Hawk",
    size: "Small", type: "Beast",
    ac: 12, hp: 7, init: 2, cr: "1/8",
    environments: [ "coast", "grassland", "mountain" ],
  },
  {
    section: "Misc Creatures", name: "Boar",
    size: "Medium", type: "Beast",
    ac: 11, hp: 11, init: 0, cr: "1/4",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Brown Bear",
    size: "Large", type: "Beast",
    ac: 11, hp: 34, init: 0, cr: "1",
    environments: [ "cave", "forest" ],
  },
  {
    section: "Misc Creatures", name: "Camel",
    size: "Large", type: "Beast",
    ac: 9, hp: 15, init: -1, cr: "1/8",
    environments: [ "desert" ],
  },
  {
    section: "Misc Creatures", name: "Cat",
    size: "Tiny", type: "Beast",
    ac: 12, hp: 2, init: 2, cr: "0",
    environments: [ "urban" ],
  },
  {
    section: "Misc Creatures", name: "Constrictor Snake",
    size: "Large", type: "Beast",
    ac: 12, hp: 13, init: 2, cr: "1/4",
    environments: [ "forest", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Crab",
    size: "Tiny", type: "Beast",
    ac: 11, hp: 2, init: 0, cr: "0",
    environments: [ "aquatic", "coast" ],
  },
  {
    section: "Misc Creatures", name: "Crocodile",
    size: "Large", type: "Beast",
    ac: 12, hp: 19, init: 0, cr: "1/2",
    environments: [ "aquatic", "coast", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Death Dog",
    size: "Medium", type: "Monstrosity",
    ac: 12, hp: 39, init: 2, cr: "1",
    environments: [ "desert", "grassland", "underground" ],
  },
  {
    section: "Misc Creatures", name: "Deer",
    size: "Medium", type: "Beast",
    ac: 13, hp: 4, init: 3, cr: "0",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Dire Wolf",
    size: "Large", type: "Beast",
    ac: 14, hp: 37, init: 2, cr: "1",
    environments: [ "arctic", "cave", "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Draft Horse",
    size: "Large", type: "Beast",
    ac: 10, hp: 19, init: 0, cr: "1/4",
    environments: [ "urban" ],
  },
  {
    section: "Misc Creatures", name: "Eagle",
    size: "Small", type: "Beast",
    ac: 12, hp: 3, init: 2, cr: "0",
    environments: [ "arctic", "grassland", "mountain" ],
  },
  {
    section: "Misc Creatures", name: "Elephant",
    size: "Huge", type: "Beast",
    ac: 12, hp: 76, init: -1, cr: "4",
    environments: [ "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Elk",
    size: "Large", type: "Beast",
    ac: 10, hp: 13, init: 0, cr: "1/4",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Flying Snake",
    size: "Tiny", type: "Beast",
    ac: 14, hp: 5, init: 4, cr: "1/8",
    environments: [ "forest", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Frog",
    size: "Tiny", type: "Beast",
    ac: 11, hp: 1, init: 1, cr: "0",
    environments: [ "aquatic", "coast", "forest", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Giant Ape",
    size: "Huge", type: "Beast",
    ac: 12, hp: 157, init: 2, cr: "7",
    environments: [ "forest" ],
  },
  {
    section: "Misc Creatures", name: "Giant Badger",
    size: "Medium", type: "Beast",
    ac: 10, hp: 13, init: 0, cr: "1/4",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Giant Bat",
    size: "Large", type: "Beast",
    ac: 13, hp: 22, init: 3, cr: "1/4",
    environments: [ "cave", "dungeon", "forest", "ruins", "swamp", "underground" ],
  },
  {
    section: "Misc Creatures", name: "Giant Boar",
    size: "Large", type: "Beast",
    ac: 12, hp: 42, init: 0, cr: "2",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Giant Centipede",
    size: "Small", type: "Beast",
    ac: 13, hp: 4, init: 2, cr: "1/4",
    environments: [ "cave", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground" ],
  },
  {
    section: "Misc Creatures", name: "Giant Constrictor Snake",
    size: "Huge", type: "Beast",
    ac: 12, hp: 60, init: 2, cr: "2",
    environments: [ "forest", "grassland", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Giant Crab",
    size: "Medium", type: "Beast",
    ac: 15, hp: 13, init: 2, cr: "1/8",
    environments: [ "aquatic", "coast" ],
  },
  {
    section: "Misc Creatures", name: "Giant Crocodile",
    size: "Huge", type: "Beast",
    ac: 14, hp: 85, init: -1, cr: "5",
    environments: [ "aquatic", "coast", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Giant Eagle",
    size: "Large", type: "Beast",
    ac: 13, hp: 26, init: 3, cr: "1",
    environments: [ "grassland", "mountain" ],
  },
  {
    section: "Misc Creatures", name: "Giant Elk",
    size: "Huge", type: "Beast",
    ac: 14, hp: 42, init: 3, cr: "2",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Giant Fire Beetle",
    size: "Small", type: "Beast",
    ac: 13, hp: 4, init: 0, cr: "0",
    environments: [ "cave", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground" ],
  },
  {
    section: "Misc Creatures", name: "Giant Frog",
    size: "Medium", type: "Beast",
    ac: 11, hp: 18, init: 1, cr: "1/4",
    environments: [ "aquatic", "coast", "forest", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Giant Goat",
    size: "Large", type: "Beast",
    ac: 11, hp: 19, init: 0, cr: "1/2",
    environments: [ "forest", "grassland", "mountain" ],
  },
  {
    section: "Misc Creatures", name: "Giant Hyena",
    size: "Large", type: "Beast",
    ac: 12, hp: 45, init: 2, cr: "1",
    environments: [ "coast", "desert", "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Giant Lizard",
    size: "Large", type: "Beast",
    ac: 12, hp: 19, init: 1, cr: "1/4",
    environments: [ "cave", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground" ],
  },
  {
    section: "Misc Creatures", name: "Giant Octopus",
    size: "Large", type: "Beast",
    ac: 11, hp: 52, init: 1, cr: "1",
    environments: [ "aquatic" ],
  },
  {
    section: "Misc Creatures", name: "Giant Owl",
    size: "Large", type: "Beast",
    ac: 12, hp: 19, init: 2, cr: "1/4",
    environments: [ "forest", "grassland", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Giant Poisonous Snake",
    size: "Medium", type: "Beast",
    ac: 14, hp: 11, init: 4, cr: "1/4",
    environments: [ "forest", "grassland", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Giant Rat",
    size: "Small", type: "Beast",
    ac: 12, hp: 7, init: 2, cr: "1/8",
    environments: [ "cave", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Giant Scorpion",
    size: "Large", type: "Beast",
    ac: 15, hp: 52, init: 1, cr: "3",
    environments: [ "cave", "coast", "desert", "dungeon", "grassland", "ruins", "swamp", "underground" ],
  },
  {
    section: "Misc Creatures", name: "Giant Sea Horse",
    size: "Large", type: "Beast",
    ac: 13, hp: 16, init: 2, cr: "1/2",
    environments: [ "aquatic" ],
  },
  {
    section: "Misc Creatures", name: "Giant Shark",
    size: "Huge", type: "Beast",
    ac: 13, hp: 126, init: 0, cr: "5",
    environments: [ "aquatic" ],
  },
  {
    section: "Misc Creatures", name: "Giant Spider",
    size: "Large", type: "Beast",
    ac: 14, hp: 26, init: 3, cr: "1",
    environments: [ "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Giant Toad",
    size: "Large", type: "Beast",
    ac: 11, hp: 39, init: 1, cr: "1",
    environments: [ "aquatic", "coast", "forest", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Giant Vulture",
    size: "Large", type: "Beast",
    ac: 10, hp: 22, init: 13, cr: "1",
    environments: [ "desert", "grassland", "ruins" ],
  },
  {
    section: "Misc Creatures", name: "Giant Wasp",
    size: "Medium", type: "Beast",
    ac: 12, hp: 13, init: 2, cr: "1/2",
    environments: [ "forest" ],
  },
  {
    section: "Misc Creatures", name: "Giant Weasel",
    size: "Medium", type: "Beast",
    ac: 13, hp: 9, init: 3, cr: "1/8",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Giant Wolf Spider",
    size: "Medium", type: "Beast",
    ac: 13, hp: 11, init: 3, cr: "1/4",
    environments: [ "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Goat",
    size: "Medium", type: "Beast",
    ac: 10, hp: 4, init: 0, cr: "0",
    environments: [ "grassland", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Hawk",
    size: "Tiny", type: "Beast",
    ac: 13, hp: 1, init: 3, cr: "0",
    environments: [ "grassland", "mountain" ],
  },
  {
    section: "Misc Creatures", name: "Hunter Shark",
    size: "Large", type: "Beast",
    ac: 12, hp: 45, init: 1, cr: "2",
    environments: [ "aquatic" ],
  },
  {
    section: "Misc Creatures", name: "Hyena",
    size: "Medium", type: "Beast",
    ac: 11, hp: 5, init: 1, cr: "0",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Jackal",
    size: "Small", type: "Beast",
    ac: 12, hp: 3, init: 2, cr: "0",
    environments: [ "desert", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Killer Whale",
    size: "Huge", type: "Beast",
    ac: 12, hp: 90, init: 0, cr: "3",
    environments: [ "aquatic" ],
  },
  {
    section: "Misc Creatures", name: "Lion",
    size: "Large", type: "Beast",
    ac: 12, hp: 26, init: 2, cr: "1",
    environments: [ "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Lizard",
    size: "Tiny", type: "Beast",
    ac: 10, hp: 2, init: 0, cr: "0",
    environments: [ "cave", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground" ],
  },
  {
    section: "Misc Creatures", name: "Mammoth",
    size: "Huge", type: "Beast",
    ac: 13, hp: 126, init: -1, cr: "6",
    environments: [ "arctic" ],
  },
  {
    section: "Misc Creatures", name: "Mastiff",
    size: "Medium", type: "Beast",
    ac: 12, hp: 5, init: 2, cr: "1/8",
    environments: [ "urban" ],
  },
  {
    section: "Misc Creatures", name: "Mule",
    size: "Medium", type: "Beast",
    ac: 10, hp: 11, init: 0, cr: "1/8",
    environments: [ "urban" ],
  },
  {
    section: "Misc Creatures", name: "Octopus",
    size: "Small", type: "Beast",
    ac: 12, hp: 3, init: 2, cr: "0",
    environments: [ "aquatic" ],
  },
  {
    section: "Misc Creatures", name: "Owl",
    size: "Tiny", type: "Beast",
    ac: 11, hp: 1, init: 1, cr: "0",
    environments: [ "forest", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Panther",
    size: "Medium", type: "Beast",
    ac: 12, hp: 13, init: 2, cr: "1/4",
    environments: [ "forest" ],
  },
  {
    section: "Misc Creatures", name: "Phase Spider",
    size: "Large", type: "Monstrosity",
    ac: 13, hp: 32, init: 2, cr: "3",
    environments: [ "cave", "coast", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "planar" ],
  },
  {
    section: "Misc Creatures", name: "Poisonous Snake",
    size: "Tiny", type: "Beast",
    ac: 13, hp: 2, init: 3, cr: "1/8",
    environments: [ "desert", "forest", "grassland", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Polar Bear",
    size: "Large", type: "Beast",
    ac: 12, hp: 42, init: 0, cr: "2",
    environments: [ "arctic", "cave" ],
  },
  {
    section: "Misc Creatures", name: "Pony",
    size: "Medium", type: "Beast",
    ac: 10, hp: 11, init: 0, cr: "1/8",
    environments: [ "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Quipper",
    size: "Tiny", type: "Beast",
    ac: 13, hp: 1, init: 3, cr: "0",
    environments: [ "aquatic" ],
  },
  {
    section: "Misc Creatures", name: "Rat",
    size: "Tiny", type: "Beast",
    ac: 10, hp: 1, init: 0, cr: "0",
    environments: [ "arctic", "cave", "coast", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Raven",
    size: "Tiny", type: "Beast",
    ac: 12, hp: 1, init: 2, cr: "0",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Reef Shark",
    size: "Medium", type: "Beast",
    ac: 12, hp: 22, init: 1, cr: "1/2",
    environments: [ "aquatic" ],
  },
  {
    section: "Misc Creatures", name: "Rhinoceros",
    size: "Large", type: "Beast",
    ac: 11, hp: 45, init: -1, cr: "2",
    environments: [ "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Riding Horse",
    size: "Large", type: "Beast",
    ac: 10, hp: 13, init: 0, cr: "1/4",
    environments: [ "urban" ],
  },
  {
    section: "Misc Creatures", name: "Saber-Toothed Tiger",
    size: "Large", type: "Beast",
    ac: 12, hp: 52, init: 2, cr: "2",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Scorpion",
    size: "Tiny", type: "Beast",
    ac: 11, hp: 1, init: 0, cr: "0",
    environments: [ "cave", "desert", "grassland", "mountain", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Sea Horse",
    size: "Tiny", type: "Beast",
    ac: 11, hp: 1, init: 1, cr: "0",
    environments: [ "aquatic" ],
  },
  {
    section: "Misc Creatures", name: "Spider",
    size: "Tiny", type: "Beast",
    ac: 12, hp: 1, init: 2, cr: "0",
    environments: [ "cave", "coast", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "planar" ],
  },
  {
    section: "Misc Creatures", name: "Swarm of Bats",
    size: "Medium", type: "Beast", tags: [ "Swarm" ],
    ac: 12, hp: 22, init: 2, cr: "1/4",
    environments: [ "cave", "dungeon", "forest", "ruins", "swamp", "underground", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Swarm of Insects",
    size: "Medium", type: "Beast", tags: [ "Swarm" ],
    ac: 12, hp: 22, init: 1, cr: "1/2",
    environments: [ "cave", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Swarm of Poisonous Snakes",
    size: "Medium", type: "Beast", tags: [ "Swarm" ],
    ac: 14, hp: 36, init: 4, cr: "2",
    environments: [ "desert", "dungeon", "forest", "grassland", "swamp" ],
  },
  {
    section: "Misc Creatures", name: "Swarm of Quippers",
    size: "Medium", type: "Beast", tags: [ "Swarm" ],
    ac: 13, hp: 28, init: 3, cr: "1",
    environments: [ "aquatic" ],
  },
  {
    section: "Misc Creatures", name: "Swarm of Rats",
    size: "Medium", type: "Beast", tags: [ "Swarm" ],
    ac: 10, hp: 24, init: 0, cr: "1/4",
    environments: [ "cave", "dungeon", "forest", "grassland", "ruins", "swamp", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Swarm of Ravens",
    size: "Medium", type: "Beast", tags: [ "Swarm" ],
    ac: 12, hp: 24, init: 2, cr: "1/4",
    environments: [ "forest", "grassland", "mountain", "ruins", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Tiger",
    size: "Large", type: "Beast",
    ac: 12, hp: 37, init: 2, cr: "1",
    environments: [ "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Vulture",
    size: "Medium", type: "Beast",
    ac: 10, hp: 5, init: 0, cr: "0",
    environments: [ "desert", "grassland", "ruins" ],
  },
  {
    section: "Misc Creatures", name: "Warhorse",
    size: "Large", type: "Beast",
    ac: 11, hp: 19, init: 1, cr: "1/2",
    environments: [ "grassland", "urban" ],
  },
  {
    section: "Misc Creatures", name: "Weasel",
    size: "Tiny", type: "Beast",
    ac: 13, hp: 1, init: 3, cr: "0",
    environments: [ "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Winter Wolf",
    size: "Large", type: "Monstrosity",
    ac: 13, hp: 75, init: 1, cr: "3",
    environments: [ "arctic", "cave", "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Wolf",
    size: "Medium", type: "Beast",
    ac: 13, hp: 11, init: 2, cr: "1/4",
    environments: [ "arctic", "cave", "forest", "grassland" ],
  },
  {
    section: "Misc Creatures", name: "Worg",
    size: "Large", type: "Monstrosity",
    ac: 13, hp: 26, init: 1, cr: "1/2",
    environments: [ "arctic", "cave", "forest", "grassland" ],
  },

  // Monster Manual Appendix: Nonplayer Characters

  {
    section: "NPCs", name: "Acolyte",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 10, hp: 9, init: 0, cr: "1/4",
    environments: [ "arctic", "desert", "dungeon", "forest", "grassland", "mountain", "swamp", "underground", "urban" ],
  },
  {
    section: "NPCs", name: "Archmage",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: "12 (15 with mage armor)", hp: 99, init: 2, cr: "12",
    environments: [ "ruins", "urban" ],
  },
  {
    section: "NPCs", name: "Assassin",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 15, hp: 78, init: 3, cr: "8",
    environments: [ "arctic", "cave", "coast", "desert", "dungeon", "forest", "grassland", "mountain", "ruins", "swamp", "underground", "urban" ],
  },
  {
    section: "NPCs", name: "Bandit",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 12, hp: 11, init: 1, cr: "1/8",
    environments: [ "arctic", "coast", "desert", "forest", "grassland", "mountain", "ruins", "urban" ],
  },
  {
    section: "NPCs", name: "Bandit Captain",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 15, hp: 65, init: 3, cr: "2",
    environments: [ "arctic", "coast", "desert", "forest", "grassland", "mountain", "ruins", "urban" ],
  },
  {
    section: "NPCs", name: "Berserker",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 13, hp: 67, init: 1, cr: "2",
    environments: [ "arctic", "cave", "desert", "forest", "grassland", "mountain", "swamp", "urban" ],
  },
  {
    section: "NPCs", name: "Commoner",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 10, hp: 4, init: 0, cr: "0",
    environments: [ "urban" ],
  },
  {
    section: "NPCs", name: "Cult Fanatic",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 13, hp: 33, init: 2, cr: "2",
    environments: [ "dungeon", "urban" ],
  },
  {
    section: "NPCs", name: "Cultist",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 12, hp: 9, init: 1, cr: "1/8",
    environments: [ "dungeon", "urban" ],
  },
  {
    section: "NPCs", name: "Druid",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 11, hp: 27, init: 1, cr: "2",
    environments: [ "arctic", "cave", "coast", "desert", "forest", "grassland", "mountain", "swamp", "underground" ],
  },
  {
    section: "NPCs", name: "Gladiator",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 16, hp: 112, init: 2, cr: "5",
    environments: [ "urban" ],
  },
  {
    section: "NPCs", name: "Guard",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 16, hp: 11, init: 1, cr: "1/8",
    environments: [ "urban" ],
  },
  {
    section: "NPCs", name: "Knight",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 18, hp: 52, init: 0, cr: "3",
    environments: [ "urban" ],
  },
  {
    section: "NPCs", name: "Mage",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: "12 (15 with mage armor)", hp: 40, init: 2, cr: "6",
    environments: [ "urban" ],
  },
  {
    section: "NPCs", name: "Noble",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 15, hp: 9, init: 1, cr: "1/8",
    environments: [ "urban" ],
  },
  {
    section: "NPCs", name: "Priest",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 13, hp: 27, init: 0, cr: "2",
    environments: [ "urban" ],
  },
  {
    section: "NPCs", name: "Scout",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 13, hp: 16, init: 2, cr: "1/2",
    environments: [ "arctic", "coast", "desert", "forest", "grassland", "mountain", "swamp" ],
  },
  {
    section: "NPCs", name: "Spy",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 12, hp: 27, init: 2, cr: "1",
    environments: [ "arctic", "cave", "coast", "desert", "forest", "grassland", "mountain", "ruins", "swamp", "urban" ],
  },
  {
    section: "NPCs", name: "Thug",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 11, hp: 32, init: 0, cr: "1/2",
    environments: [ "arctic", "cave", "coast", "forest", "grassland", "urban" ],
  },
  {
    section: "NPCs", name: "Tribal Warrior",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 12, hp: 11, init: 0, cr: "1/8",
    environments: [ "arctic", "cave", "desert", "forest", "grassland", "mountain", "swamp" ],
  },
  {
    section: "NPCs", name: "Veteran",
    size: "Medium", type: "Humanoid", tags: [ "any" ],
    ac: 17, hp: 58, init: 1, cr: "3",
    environments: [ "urban" ],
  },
], (monster) => {
  return monster.name.replace(' ', '_').toLowerCase();
});
